# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: star.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nstar.proto\x12\tstarguide\"\x07\n\x05\x45mpty\")\n\x17\x46indFavoriteUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\">\n\x19\x43reateFavoriteUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x11\n\tproductId\x18\x02 \x01(\t\">\n\x19\x44\x65leteFavoriteUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x11\n\tproductId\x18\x02 \x01(\t\"E\n\x14\x46\x61voriteUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x11\n\tproductId\x18\x03 \x01(\t\"K\n\x15\x46\x61voriteUsersResponse\x12\x32\n\tfavorites\x18\x01 \x03(\x0b\x32\x1f.starguide.FavoriteUserResponse2\x83\x02\n\x0bStarService\x12Q\n\x06Insert\x12$.starguide.CreateFavoriteUserRequest\x1a\x1f.starguide.FavoriteUserResponse\"\x00\x12Q\n\x06\x44\x65lete\x12$.starguide.DeleteFavoriteUserRequest\x1a\x1f.starguide.FavoriteUserResponse\"\x00\x12N\n\x04\x46ind\x12\".starguide.FindFavoriteUserRequest\x1a .starguide.FavoriteUsersResponse\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_FINDFAVORITEUSERREQUEST = DESCRIPTOR.message_types_by_name['FindFavoriteUserRequest']
_CREATEFAVORITEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateFavoriteUserRequest']
_DELETEFAVORITEUSERREQUEST = DESCRIPTOR.message_types_by_name['DeleteFavoriteUserRequest']
_FAVORITEUSERRESPONSE = DESCRIPTOR.message_types_by_name['FavoriteUserResponse']
_FAVORITEUSERSRESPONSE = DESCRIPTOR.message_types_by_name['FavoriteUsersResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'star_pb2'
  # @@protoc_insertion_point(class_scope:starguide.Empty)
  })
_sym_db.RegisterMessage(Empty)

FindFavoriteUserRequest = _reflection.GeneratedProtocolMessageType('FindFavoriteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDFAVORITEUSERREQUEST,
  '__module__' : 'star_pb2'
  # @@protoc_insertion_point(class_scope:starguide.FindFavoriteUserRequest)
  })
_sym_db.RegisterMessage(FindFavoriteUserRequest)

CreateFavoriteUserRequest = _reflection.GeneratedProtocolMessageType('CreateFavoriteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFAVORITEUSERREQUEST,
  '__module__' : 'star_pb2'
  # @@protoc_insertion_point(class_scope:starguide.CreateFavoriteUserRequest)
  })
_sym_db.RegisterMessage(CreateFavoriteUserRequest)

DeleteFavoriteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteFavoriteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFAVORITEUSERREQUEST,
  '__module__' : 'star_pb2'
  # @@protoc_insertion_point(class_scope:starguide.DeleteFavoriteUserRequest)
  })
_sym_db.RegisterMessage(DeleteFavoriteUserRequest)

FavoriteUserResponse = _reflection.GeneratedProtocolMessageType('FavoriteUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITEUSERRESPONSE,
  '__module__' : 'star_pb2'
  # @@protoc_insertion_point(class_scope:starguide.FavoriteUserResponse)
  })
_sym_db.RegisterMessage(FavoriteUserResponse)

FavoriteUsersResponse = _reflection.GeneratedProtocolMessageType('FavoriteUsersResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVORITEUSERSRESPONSE,
  '__module__' : 'star_pb2'
  # @@protoc_insertion_point(class_scope:starguide.FavoriteUsersResponse)
  })
_sym_db.RegisterMessage(FavoriteUsersResponse)

_STARSERVICE = DESCRIPTOR.services_by_name['StarService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=25
  _EMPTY._serialized_end=32
  _FINDFAVORITEUSERREQUEST._serialized_start=34
  _FINDFAVORITEUSERREQUEST._serialized_end=75
  _CREATEFAVORITEUSERREQUEST._serialized_start=77
  _CREATEFAVORITEUSERREQUEST._serialized_end=139
  _DELETEFAVORITEUSERREQUEST._serialized_start=141
  _DELETEFAVORITEUSERREQUEST._serialized_end=203
  _FAVORITEUSERRESPONSE._serialized_start=205
  _FAVORITEUSERRESPONSE._serialized_end=274
  _FAVORITEUSERSRESPONSE._serialized_start=276
  _FAVORITEUSERSRESPONSE._serialized_end=351
  _STARSERVICE._serialized_start=354
  _STARSERVICE._serialized_end=613
# @@protoc_insertion_point(module_scope)
