# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import star_pb2 as star__pb2


class StarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/starguide.StarService/Insert',
                request_serializer=star__pb2.CreateFavoriteUserRequest.SerializeToString,
                response_deserializer=star__pb2.FavoriteUserResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/starguide.StarService/Delete',
                request_serializer=star__pb2.DeleteFavoriteUserRequest.SerializeToString,
                response_deserializer=star__pb2.FavoriteUserResponse.FromString,
                )
        self.Find = channel.unary_unary(
                '/starguide.StarService/Find',
                request_serializer=star__pb2.FindFavoriteUserRequest.SerializeToString,
                response_deserializer=star__pb2.FavoriteUsersResponse.FromString,
                )


class StarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=star__pb2.CreateFavoriteUserRequest.FromString,
                    response_serializer=star__pb2.FavoriteUserResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=star__pb2.DeleteFavoriteUserRequest.FromString,
                    response_serializer=star__pb2.FavoriteUserResponse.SerializeToString,
            ),
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=star__pb2.FindFavoriteUserRequest.FromString,
                    response_serializer=star__pb2.FavoriteUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'starguide.StarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starguide.StarService/Insert',
            star__pb2.CreateFavoriteUserRequest.SerializeToString,
            star__pb2.FavoriteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starguide.StarService/Delete',
            star__pb2.DeleteFavoriteUserRequest.SerializeToString,
            star__pb2.FavoriteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starguide.StarService/Find',
            star__pb2.FindFavoriteUserRequest.SerializeToString,
            star__pb2.FavoriteUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
