# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\tuserguide\"\x07\n\x05\x45mpty\"\x18\n\nUserItemId\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x07NewItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08userHash\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"6\n\x08UserItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08userHash\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\".\n\x08UserList\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.userguide.UserItem2\xb1\x03\n\x0bUserService\x12/\n\x04List\x12\x10.userguide.Empty\x1a\x13.userguide.UserList\"\x00\x12\x33\n\x06Insert\x12\x12.userguide.NewItem\x1a\x13.userguide.UserItem\"\x00\x12\x34\n\x04\x46ind\x12\x15.userguide.UserItemId\x1a\x13.userguide.UserItem\"\x00\x12\x36\n\x06\x44\x65lete\x12\x15.userguide.UserItemId\x1a\x13.userguide.UserItem\"\x00\x12=\n\x10ListStreamServer\x12\x10.userguide.Empty\x1a\x13.userguide.UserItem\"\x00\x30\x01\x12\x42\n\x10ListStreamClient\x12\x15.userguide.UserItemId\x1a\x13.userguide.UserList\"\x00(\x01\x12K\n\x17ListStreamBidirectional\x12\x15.userguide.UserItemId\x1a\x13.userguide.UserItem\"\x00(\x01\x30\x01\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_USERITEMID = DESCRIPTOR.message_types_by_name['UserItemId']
_NEWITEM = DESCRIPTOR.message_types_by_name['NewItem']
_USERITEM = DESCRIPTOR.message_types_by_name['UserItem']
_USERLIST = DESCRIPTOR.message_types_by_name['UserList']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:userguide.Empty)
  })
_sym_db.RegisterMessage(Empty)

UserItemId = _reflection.GeneratedProtocolMessageType('UserItemId', (_message.Message,), {
  'DESCRIPTOR' : _USERITEMID,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:userguide.UserItemId)
  })
_sym_db.RegisterMessage(UserItemId)

NewItem = _reflection.GeneratedProtocolMessageType('NewItem', (_message.Message,), {
  'DESCRIPTOR' : _NEWITEM,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:userguide.NewItem)
  })
_sym_db.RegisterMessage(NewItem)

UserItem = _reflection.GeneratedProtocolMessageType('UserItem', (_message.Message,), {
  'DESCRIPTOR' : _USERITEM,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:userguide.UserItem)
  })
_sym_db.RegisterMessage(UserItem)

UserList = _reflection.GeneratedProtocolMessageType('UserList', (_message.Message,), {
  'DESCRIPTOR' : _USERLIST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:userguide.UserList)
  })
_sym_db.RegisterMessage(UserList)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=25
  _EMPTY._serialized_end=32
  _USERITEMID._serialized_start=34
  _USERITEMID._serialized_end=58
  _NEWITEM._serialized_start=60
  _NEWITEM._serialized_end=113
  _USERITEM._serialized_start=115
  _USERITEM._serialized_end=169
  _USERLIST._serialized_start=171
  _USERLIST._serialized_end=217
  _USERSERVICE._serialized_start=220
  _USERSERVICE._serialized_end=653
# @@protoc_insertion_point(module_scope)
